name: dist_py_module_build_python2_package
on:
  push:
    branches: [ master ]
    paths:
      - 'dist_py_module/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'dist_py_module/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dist_py_module set up python2
      uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - name: dist_py_module install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt
    - name: dist_py_module python2 package build
      run: |
        python setup.py --github sdist bdist_wheel
