templates:
    - package:
        - setup_package.template
        - MANIFEST.template
        - pyproject.template
        - setup.template
    - tool:
        - setup_tool.template
        - MANIFEST.template
        - pyproject.template
        - setup.template
    - cancel: null

modules:
    - setup.py
    - MANIFEST.in
    - pyproject.toml
    - setup.cfg
